// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gnss.proto

package com.demo.grpc.gnss;

/**
 * Protobuf type {@code GeodeticCoordHDtoGrpc}
 */
public final class GeodeticCoordHDtoGrpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GeodeticCoordHDtoGrpc)
    GeodeticCoordHDtoGrpcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GeodeticCoordHDtoGrpc.newBuilder() to construct.
  private GeodeticCoordHDtoGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GeodeticCoordHDtoGrpc() {
    referenceType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GeodeticCoordHDtoGrpc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GeodeticCoordHDtoGrpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            lon_ = input.readDouble();
            break;
          }
          case 17: {

            lat_ = input.readDouble();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            referenceType_ = s;
            break;
          }
          case 33: {

            h_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.demo.grpc.gnss.GnssProto.internal_static_GeodeticCoordHDtoGrpc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.demo.grpc.gnss.GnssProto.internal_static_GeodeticCoordHDtoGrpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.demo.grpc.gnss.GeodeticCoordHDtoGrpc.class, com.demo.grpc.gnss.GeodeticCoordHDtoGrpc.Builder.class);
  }

  public static final int LON_FIELD_NUMBER = 1;
  private double lon_;
  /**
   * <pre>
   **
   * 大地经度
   * </pre>
   *
   * <code>double lon = 1;</code>
   * @return The lon.
   */
  @java.lang.Override
  public double getLon() {
    return lon_;
  }

  public static final int LAT_FIELD_NUMBER = 2;
  private double lat_;
  /**
   * <pre>
   **
   * 大地纬度
   * </pre>
   *
   * <code>double lat = 2;</code>
   * @return The lat.
   */
  @java.lang.Override
  public double getLat() {
    return lat_;
  }

  public static final int REFERENCE_TYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object referenceType_;
  /**
   * <pre>
   **
   * 空间参考系类型
   * </pre>
   *
   * <code>string reference_type = 3;</code>
   * @return The referenceType.
   */
  @java.lang.Override
  public java.lang.String getReferenceType() {
    java.lang.Object ref = referenceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      referenceType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 空间参考系类型
   * </pre>
   *
   * <code>string reference_type = 3;</code>
   * @return The bytes for referenceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReferenceTypeBytes() {
    java.lang.Object ref = referenceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      referenceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int H_FIELD_NUMBER = 4;
  private double h_;
  /**
   * <pre>
   **
   * 大地高
   * </pre>
   *
   * <code>double h = 4;</code>
   * @return The h.
   */
  @java.lang.Override
  public double getH() {
    return h_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lon_ != 0D) {
      output.writeDouble(1, lon_);
    }
    if (lat_ != 0D) {
      output.writeDouble(2, lat_);
    }
    if (!getReferenceTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, referenceType_);
    }
    if (h_ != 0D) {
      output.writeDouble(4, h_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lon_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, lon_);
    }
    if (lat_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, lat_);
    }
    if (!getReferenceTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, referenceType_);
    }
    if (h_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, h_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.demo.grpc.gnss.GeodeticCoordHDtoGrpc)) {
      return super.equals(obj);
    }
    com.demo.grpc.gnss.GeodeticCoordHDtoGrpc other = (com.demo.grpc.gnss.GeodeticCoordHDtoGrpc) obj;

    if (java.lang.Double.doubleToLongBits(getLon())
        != java.lang.Double.doubleToLongBits(
            other.getLon())) return false;
    if (java.lang.Double.doubleToLongBits(getLat())
        != java.lang.Double.doubleToLongBits(
            other.getLat())) return false;
    if (!getReferenceType()
        .equals(other.getReferenceType())) return false;
    if (java.lang.Double.doubleToLongBits(getH())
        != java.lang.Double.doubleToLongBits(
            other.getH())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLon()));
    hash = (37 * hash) + LAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLat()));
    hash = (37 * hash) + REFERENCE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getReferenceType().hashCode();
    hash = (37 * hash) + H_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getH()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.demo.grpc.gnss.GeodeticCoordHDtoGrpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GeodeticCoordHDtoGrpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GeodeticCoordHDtoGrpc)
      com.demo.grpc.gnss.GeodeticCoordHDtoGrpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.grpc.gnss.GnssProto.internal_static_GeodeticCoordHDtoGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.grpc.gnss.GnssProto.internal_static_GeodeticCoordHDtoGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.grpc.gnss.GeodeticCoordHDtoGrpc.class, com.demo.grpc.gnss.GeodeticCoordHDtoGrpc.Builder.class);
    }

    // Construct using com.demo.grpc.gnss.GeodeticCoordHDtoGrpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      lon_ = 0D;

      lat_ = 0D;

      referenceType_ = "";

      h_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.demo.grpc.gnss.GnssProto.internal_static_GeodeticCoordHDtoGrpc_descriptor;
    }

    @java.lang.Override
    public com.demo.grpc.gnss.GeodeticCoordHDtoGrpc getDefaultInstanceForType() {
      return com.demo.grpc.gnss.GeodeticCoordHDtoGrpc.getDefaultInstance();
    }

    @java.lang.Override
    public com.demo.grpc.gnss.GeodeticCoordHDtoGrpc build() {
      com.demo.grpc.gnss.GeodeticCoordHDtoGrpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.demo.grpc.gnss.GeodeticCoordHDtoGrpc buildPartial() {
      com.demo.grpc.gnss.GeodeticCoordHDtoGrpc result = new com.demo.grpc.gnss.GeodeticCoordHDtoGrpc(this);
      result.lon_ = lon_;
      result.lat_ = lat_;
      result.referenceType_ = referenceType_;
      result.h_ = h_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.demo.grpc.gnss.GeodeticCoordHDtoGrpc) {
        return mergeFrom((com.demo.grpc.gnss.GeodeticCoordHDtoGrpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.demo.grpc.gnss.GeodeticCoordHDtoGrpc other) {
      if (other == com.demo.grpc.gnss.GeodeticCoordHDtoGrpc.getDefaultInstance()) return this;
      if (other.getLon() != 0D) {
        setLon(other.getLon());
      }
      if (other.getLat() != 0D) {
        setLat(other.getLat());
      }
      if (!other.getReferenceType().isEmpty()) {
        referenceType_ = other.referenceType_;
        onChanged();
      }
      if (other.getH() != 0D) {
        setH(other.getH());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.demo.grpc.gnss.GeodeticCoordHDtoGrpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.demo.grpc.gnss.GeodeticCoordHDtoGrpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double lon_ ;
    /**
     * <pre>
     **
     * 大地经度
     * </pre>
     *
     * <code>double lon = 1;</code>
     * @return The lon.
     */
    @java.lang.Override
    public double getLon() {
      return lon_;
    }
    /**
     * <pre>
     **
     * 大地经度
     * </pre>
     *
     * <code>double lon = 1;</code>
     * @param value The lon to set.
     * @return This builder for chaining.
     */
    public Builder setLon(double value) {
      
      lon_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 大地经度
     * </pre>
     *
     * <code>double lon = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLon() {
      
      lon_ = 0D;
      onChanged();
      return this;
    }

    private double lat_ ;
    /**
     * <pre>
     **
     * 大地纬度
     * </pre>
     *
     * <code>double lat = 2;</code>
     * @return The lat.
     */
    @java.lang.Override
    public double getLat() {
      return lat_;
    }
    /**
     * <pre>
     **
     * 大地纬度
     * </pre>
     *
     * <code>double lat = 2;</code>
     * @param value The lat to set.
     * @return This builder for chaining.
     */
    public Builder setLat(double value) {
      
      lat_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 大地纬度
     * </pre>
     *
     * <code>double lat = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLat() {
      
      lat_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object referenceType_ = "";
    /**
     * <pre>
     **
     * 空间参考系类型
     * </pre>
     *
     * <code>string reference_type = 3;</code>
     * @return The referenceType.
     */
    public java.lang.String getReferenceType() {
      java.lang.Object ref = referenceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referenceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 空间参考系类型
     * </pre>
     *
     * <code>string reference_type = 3;</code>
     * @return The bytes for referenceType.
     */
    public com.google.protobuf.ByteString
        getReferenceTypeBytes() {
      java.lang.Object ref = referenceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 空间参考系类型
     * </pre>
     *
     * <code>string reference_type = 3;</code>
     * @param value The referenceType to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      referenceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 空间参考系类型
     * </pre>
     *
     * <code>string reference_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceType() {
      
      referenceType_ = getDefaultInstance().getReferenceType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 空间参考系类型
     * </pre>
     *
     * <code>string reference_type = 3;</code>
     * @param value The bytes for referenceType to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      referenceType_ = value;
      onChanged();
      return this;
    }

    private double h_ ;
    /**
     * <pre>
     **
     * 大地高
     * </pre>
     *
     * <code>double h = 4;</code>
     * @return The h.
     */
    @java.lang.Override
    public double getH() {
      return h_;
    }
    /**
     * <pre>
     **
     * 大地高
     * </pre>
     *
     * <code>double h = 4;</code>
     * @param value The h to set.
     * @return This builder for chaining.
     */
    public Builder setH(double value) {
      
      h_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 大地高
     * </pre>
     *
     * <code>double h = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearH() {
      
      h_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GeodeticCoordHDtoGrpc)
  }

  // @@protoc_insertion_point(class_scope:GeodeticCoordHDtoGrpc)
  private static final com.demo.grpc.gnss.GeodeticCoordHDtoGrpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.demo.grpc.gnss.GeodeticCoordHDtoGrpc();
  }

  public static com.demo.grpc.gnss.GeodeticCoordHDtoGrpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GeodeticCoordHDtoGrpc>
      PARSER = new com.google.protobuf.AbstractParser<GeodeticCoordHDtoGrpc>() {
    @java.lang.Override
    public GeodeticCoordHDtoGrpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GeodeticCoordHDtoGrpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GeodeticCoordHDtoGrpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GeodeticCoordHDtoGrpc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.demo.grpc.gnss.GeodeticCoordHDtoGrpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

