// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gnss.proto

package com.demo.grpc.gnss;

public final class GnssProto {
  private GnssProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeodeticCoordHDtoGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeodeticCoordHDtoGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpatialCoordDtoGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpatialCoordDtoGrpc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGnss.proto\"T\n\025GeodeticCoordHDtoGrpc\022\013\n" +
      "\003lon\030\001 \001(\001\022\013\n\003lat\030\002 \001(\001\022\026\n\016reference_typ" +
      "e\030\003 \001(\t\022\t\n\001h\030\004 \001(\001\"f\n\023SpatialCoordDtoGrp" +
      "c\022\021\n\tspatial_x\030\001 \001(\001\022\021\n\tspatial_y\030\002 \001(\001\022" +
      "\021\n\tspatial_z\030\003 \001(\001\022\026\n\016reference_type\030\004 \001" +
      "(\t2I\n\013GnssService\022:\n\010Geo2cart\022\026.Geodetic" +
      "CoordHDtoGrpc\032\024.SpatialCoordDtoGrpc\"\000B!\n" +
      "\022com.demo.grpc.gnssB\tGnssProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GeodeticCoordHDtoGrpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GeodeticCoordHDtoGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeodeticCoordHDtoGrpc_descriptor,
        new java.lang.String[] { "Lon", "Lat", "ReferenceType", "H", });
    internal_static_SpatialCoordDtoGrpc_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SpatialCoordDtoGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpatialCoordDtoGrpc_descriptor,
        new java.lang.String[] { "SpatialX", "SpatialY", "SpatialZ", "ReferenceType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
