// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gnss.proto

package com.demo.grpc.gnss;

public interface SpatialCoordDtoGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SpatialCoordDtoGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * 笛卡尔空间坐标X
   * </pre>
   *
   * <code>double spatial_x = 1;</code>
   * @return The spatialX.
   */
  double getSpatialX();

  /**
   * <code>double spatial_y = 2;</code>
   * @return The spatialY.
   */
  double getSpatialY();

  /**
   * <pre>
   **
   * 笛卡尔空间坐标Z
   * </pre>
   *
   * <code>double spatial_z = 3;</code>
   * @return The spatialZ.
   */
  double getSpatialZ();

  /**
   * <pre>
   **
   * 空间参考系类型
   * </pre>
   *
   * <code>string reference_type = 4;</code>
   * @return The referenceType.
   */
  java.lang.String getReferenceType();
  /**
   * <pre>
   **
   * 空间参考系类型
   * </pre>
   *
   * <code>string reference_type = 4;</code>
   * @return The bytes for referenceType.
   */
  com.google.protobuf.ByteString
      getReferenceTypeBytes();
}
