// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Manager.proto

package com.demo.grpc.manager;

public final class ManagerProto {
  private ManagerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UseDatumDtoGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UseDatumDtoGrpc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rManager.proto\032\033google/protobuf/empty.p" +
      "roto\"0\n\017UseDatumDtoGrpc\022\n\n\002id\030\001 \001(\005\022\021\n\td" +
      "atum_dto\030\002 \001(\t2H\n\016ManagerService\0226\n\010UseD" +
      "atum\022\020.UseDatumDtoGrpc\032\026.google.protobuf" +
      ".Empty\"\000B\'\n\025com.demo.grpc.managerB\014Manag" +
      "erProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_UseDatumDtoGrpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UseDatumDtoGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UseDatumDtoGrpc_descriptor,
        new java.lang.String[] { "Id", "DatumDto", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
