// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Manager.proto

package com.demo.grpc.manager;

public interface UseDatumDtoGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UseDatumDtoGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string datum_dto = 2;</code>
   * @return The datumDto.
   */
  java.lang.String getDatumDto();
  /**
   * <code>string datum_dto = 2;</code>
   * @return The bytes for datumDto.
   */
  com.google.protobuf.ByteString
      getDatumDtoBytes();
}
