spring:
  datasource:
    threadpool:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/xxx?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true&allowPublicKeyRetrieval=true
      username: root
      password: 123456
    clickhouse:
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      jdbc-url: jdbc:clickhouse://127.0.0.1:8123/xxx
      username: default
      password: ""




