server:
  port: 8088
  servlet:
    context-path: /service


spring:
  application:
    name: grpc-service
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR_PORT:172.16.36.61:8848}
        namespace: ${NACOS_NAMESPACE:lsy-hi-ims-dev}
        group: ${NACOS_GROUP:IMS_GROUP}
        service: ${spring.application.name}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml
        group: ${spring.cloud.nacos.discovery.group}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        # 支持多个共享 Data Id 的配置，优先级小于extension-configs,自定义 Data Id 配置 属性是个集合，内部由 Config POJO 组成。Config 有 3 个属性，分别是 dataId, group 以及 refresh
        shared-configs[0]:
          data-id: ${NACOS_COMMON:hi-ims-common}.yaml # 配置文件名-Data Id
          group: ${spring.cloud.nacos.discovery.group}   # 默认为DEFAULT_GROUP
          refresh: true   # 是否动态刷新，默认为false
  main:
    allow-circular-references: true

# gRPC有关的配置，这里只需要配置服务端口号
grpc:
  server:
    port: 9898



